### ISSUE TITLE
程序总是有错误

### ISSUE THREAD

**Issue by Ninzero** [lzps/weather#1]
我输入了彩云和thinkpage的API，但是每次程序运行都报错
`Traceback (most recent call last):
  File "/Users/Ninzero/Downloads/weather-master/main.py", line 40, in <module>
    pprint(t.now())`
  `File "/Users/Ninzero/Downloads/weather-master/thinkpage.py", line 63, in now
    t = str(self.dnow['weather'][0])`
`KeyError: 'weather'`
请问这是为什么？

**Comment by lzps** [comment]
File "/Users/Ninzero/Downloads/weather-master/**thinkpage.py**", line 63, in now t = str(self.dnow['weather'][0])

看起来是 thinkpage.py 有问题，但我刚刚用过一次，可以使用。
你可以试试单独运行 thinkpage.py 先不管 main.py 再看看有没有问题。

如果还有问题修改一下 thinkpage.py，像下面一样添加 “print(self.dnow)” 后让我看看
```
    def now(self):
        """以字典形式返回实时天气状况"""
	print(self.dnow)
        t = str(self.dnow['weather'][0])
```

另外，检查一下 config 文件（格式如下），确认 apikey 无误，输入时也不要有空格之类。
```
caiyunapp:;forecast:;thinkpage:apikeyxxx
39.93,116.40
```

**Comment by Ninzero** [comment]
我刚刚又跑了一遍程序……之前怎么都不行的程序突然就好了……总之还是多谢了，另外有可能获得当天的天气预报吗？比如说最高温度最低温度之类的？

**Comment by lzps** [comment]
获得当天的天气预报不难，就是最近我没多少时间，争取在周末试试添加新功能。

**Comment by Ninzero** [comment]
好的好的多谢🙏
